name: twin_commons
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.0.7+1
  json_annotation: ^4.8.1
  collection: ^1.17.2
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  eventify: ^1.0.1
  pinput: ^4.0.0
  easy_localization: ^3.0.1
  json_serializable: ^6.6.1
  logger: ^2.0.1
  uuid: ^4.3.3
  google_fonts: ^5.0.0
  easy_logger: ^0.0.2
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  flutter_displaymode: ^0.6.0
  community_charts_flutter: ^1.0.2
  fl_chart: ^0.68.0
  provider: ^6.1.1
  colored_json: ^1.1.2
  convex_bottom_bar: ^3.2.0
  custom_date_range_picker: ^1.0.10
  column_layout: ^1.0.0
  flutter_spinkit: ^5.2.0
  otp_text_field: ^1.1.3
  device_info_plus: ^10.0.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  pluto_menu_bar: ^3.0.1
  dropdown_search: ^5.0.6
  flutter_spinbox: ^0.13.1
  rename_app: ^1.3.1
  number_inc_dec: ^0.8.0
  accordion: ^2.6.0
  flutter_iconpicker: ^3.3.3
  flutter_colorpicker: ^1.0.3
  responsive_framework: ^1.1.1
  animations: ^2.0.7
  loading_gifs: ^0.3.0
  navigation_utils: ^0.5.2
  dotted_border: ^2.1.0
  textfield_search: ^0.10.0
  font_awesome_flutter: ^10.6.0
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  dropdown_plus: ^0.0.9
  flutter_slider_drawer_enhanced: ^2.1.6
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  super_tooltip: ^2.0.7
  progress_dialog_null_safe: ^3.0.0
  file_picker: ^8.0.0+1
  dio: ^5.3.4
  string_validator: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_font_picker: ^1.4.0
  boxy: ^2.1.3
  moment_dart: ^2.0.2
  mqtt5_client: ^4.0.3
  intl_phone_field: ^3.2.0
  synchronized: ^3.1.0+1
  gauge_indicator: ^0.4.3
  gauges: ^1.0.0
  knob_widget: ^1.0.3
  flutter_code_editor: ^0.3.1
  row_layout: ^1.0.2
  get: ^4.6.6
  fluttertoast: ^8.2.4
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_line_editor: ^6.0.0
  timeago: ^3.6.1
  data_table_2: ^2.5.10
  syncfusion_flutter_charts: ^25.1.42+1
  water_bottle: ^0.0.7
  liquid_progress_indicator_v2: ^0.5.0
  animated_battery_gauge: ^0.2.0
  code_editor: ^2.1.0
  country_codes: ^3.1.0+2
  multi_select_flutter: ^4.1.3
  pricing_cards: ^0.0.8
  webview_flutter_web: ^0.2.2+4
  toggle_switch: ^2.3.0
  flutter_session_manager: ^1.0.3
  freezed_annotation: ^2.4.1


  multi_dropdown: ^2.1.4
  select2dot1: ^2.0.9
  search_choices: ^2.2.7
  syncfusion_flutter_datagrid: ^25.2.6
  syncfusion_flutter_gauges: ^25.2.6
  percent_indicator: ^4.2.3
  syncfusion_flutter_sliders: ^25.2.7


  verification_api:
    git:
      url: https://github.com/boodskap/verification_api.git
      ref: main

  nocode_api:
    git:
      url: https://github.com/boodskap/nocode_api.git
      ref: main

  twinned_api:
    git:
      url: https://github.com/boodskap/twinned_api.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
